
version: '2'

services:

  orderer.evote.com:
    container_name: orderer.evote.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../channel-artifacts:/var/hyperledger/orderer
      - ../crypto-config/ordererOrganizations/evote.com/orderers/orderer.evote.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/evote.com/orderers/orderer.evote.com/tls/:/var/hyperledger/orderer/tls
      - orderer.evote.com:/var/hyperledger/production/orderer
    extra_hosts:
      - "peer0.jatim.evote.com:192.168.2.11"
      - "peer1.jatim.evote.com:192.168.2.11"
      - "peer0.jabar.evote.com:192.168.2.12"
      - "peer1.jabar.evote.com:192.168.2.12"
      - "ca_peerJatim:192.168.2.11"
      - "ca_peerJabar:192.168.2.12"
    ports:
      - 7050:7050
