version: '2'

services:

  orderer.evote.com:
    container_name: orderer.evote.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../channel-artifacts:/var/hyperledger/orderer
      - ../crypto-config/ordererOrganizations/evote.com/orderers/orderer.evote.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/evote.com/orderers/orderer.evote.com/tls/:/var/hyperledger/orderer/tls
      - orderer.evote.com:/var/hyperledger/production/orderer
    extra_hosts:
      - "peer0.jatim.evote.com:3.86.93.3"
      - "peer1.jatim.evote.com:3.86.93.3"
      - "peer0.jabar.evote.com:3.93.213.80"
      - "peer1.jabar.evote.com:3.93.213.80"
      - "ca_peerJatim:3.86.93.3"
      - "ca_peerJabar:3.93.213.80"
    ports:
      - 7050:7050
