version: '2'

volumes:
  peer0.jatim.evote.com:
  peer1.jatim.evote.com:
  peer2.jatim.evote.com:
  peer3.jatim.evote.com:

services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-jatim
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.jatim.evote.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/dc5bd5c9a00b2ceaca700b34cbb87a905d42d8e6ac8f1a88a84dfe9cee032b0e_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.jatim.evote.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/dc5bd5c9a00b2ceaca700b34cbb87a905d42d8e6ac8f1a88a84dfe9cee032b0e_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/jatim.evote.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerJatim

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for evote map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5983:5984"

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for evote map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "6984:5984"

  couchdb4:
    container_name: couchdb4
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for evote map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "9984:5984"

  couchdb5:
    container_name: couchdb5
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for evote map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "10984:5984"




  peer0.jatim.evote.com:
    container_name: peer0.jatim.evote.com
    extends:
      file:  base/docker-compose-base2.yaml
      service: peer0.jatim.evote.com
    depends_on:
      - couchdb0

  peer1.jatim.evote.com:
    container_name: peer1.jatim.evote.com
    extends:
      file:  base/docker-compose-base2.yaml
      service: peer1.jatim.evote.com
    depends_on:
      - couchdb1

  peer2.jatim.evote.com:
    container_name: peer2.jatim.evote.com
    extends:
      file:  base/docker-compose-base2.yaml
      service: peer2.jatim.evote.com
    depends_on:
      - couchdb4

  peer3.jatim.evote.com:
    container_name: peer3.jatim.evote.com
    extends:
      file:  base/docker-compose-base2.yaml
      service: peer3.jatim.evote.com
    depends_on:
      - couchdb5
